// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: src/api/specification/api_specification_am_fleet_management.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddCarToFleetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vin      *Vin   `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	FleetId  string `protobuf:"bytes,2,opt,name=fleetId,proto3" json:"fleetId,omitempty"`
	Location string `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
}

func (x *AddCarToFleetRequest) Reset() {
	*x = AddCarToFleetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCarToFleetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCarToFleetRequest) ProtoMessage() {}

func (x *AddCarToFleetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCarToFleetRequest.ProtoReflect.Descriptor instead.
func (*AddCarToFleetRequest) Descriptor() ([]byte, []int) {
	return file_src_api_specification_api_specification_am_fleet_management_proto_rawDescGZIP(), []int{0}
}

func (x *AddCarToFleetRequest) GetVin() *Vin {
	if x != nil {
		return x.Vin
	}
	return nil
}

func (x *AddCarToFleetRequest) GetFleetId() string {
	if x != nil {
		return x.FleetId
	}
	return ""
}

func (x *AddCarToFleetRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type AddCarToFleetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Car   *Car         `protobuf:"bytes,1,opt,name=car,proto3" json:"car,omitempty"`
	Error *ErrorDetail `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *AddCarToFleetResponse) Reset() {
	*x = AddCarToFleetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCarToFleetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCarToFleetResponse) ProtoMessage() {}

func (x *AddCarToFleetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCarToFleetResponse.ProtoReflect.Descriptor instead.
func (*AddCarToFleetResponse) Descriptor() ([]byte, []int) {
	return file_src_api_specification_api_specification_am_fleet_management_proto_rawDescGZIP(), []int{1}
}

func (x *AddCarToFleetResponse) GetCar() *Car {
	if x != nil {
		return x.Car
	}
	return nil
}

func (x *AddCarToFleetResponse) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type ListCarsInFleetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FleetId string `protobuf:"bytes,1,opt,name=fleetId,proto3" json:"fleetId,omitempty"`
}

func (x *ListCarsInFleetRequest) Reset() {
	*x = ListCarsInFleetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCarsInFleetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCarsInFleetRequest) ProtoMessage() {}

func (x *ListCarsInFleetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCarsInFleetRequest.ProtoReflect.Descriptor instead.
func (*ListCarsInFleetRequest) Descriptor() ([]byte, []int) {
	return file_src_api_specification_api_specification_am_fleet_management_proto_rawDescGZIP(), []int{2}
}

func (x *ListCarsInFleetRequest) GetFleetId() string {
	if x != nil {
		return x.FleetId
	}
	return ""
}

type ListCarsInFleetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cars  []*Car       `protobuf:"bytes,1,rep,name=cars,proto3" json:"cars,omitempty"`
	Error *ErrorDetail `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ListCarsInFleetResponse) Reset() {
	*x = ListCarsInFleetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCarsInFleetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCarsInFleetResponse) ProtoMessage() {}

func (x *ListCarsInFleetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCarsInFleetResponse.ProtoReflect.Descriptor instead.
func (*ListCarsInFleetResponse) Descriptor() ([]byte, []int) {
	return file_src_api_specification_api_specification_am_fleet_management_proto_rawDescGZIP(), []int{3}
}

func (x *ListCarsInFleetResponse) GetCars() []*Car {
	if x != nil {
		return x.Cars
	}
	return nil
}

func (x *ListCarsInFleetResponse) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type RemoveCarFromFleetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vin *Vin `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
}

func (x *RemoveCarFromFleetRequest) Reset() {
	*x = RemoveCarFromFleetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveCarFromFleetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCarFromFleetRequest) ProtoMessage() {}

func (x *RemoveCarFromFleetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCarFromFleetRequest.ProtoReflect.Descriptor instead.
func (*RemoveCarFromFleetRequest) Descriptor() ([]byte, []int) {
	return file_src_api_specification_api_specification_am_fleet_management_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveCarFromFleetRequest) GetVin() *Vin {
	if x != nil {
		return x.Vin
	}
	return nil
}

type RemoveCarFromFleetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool         `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Error  *ErrorDetail `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *RemoveCarFromFleetResponse) Reset() {
	*x = RemoveCarFromFleetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveCarFromFleetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCarFromFleetResponse) ProtoMessage() {}

func (x *RemoveCarFromFleetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCarFromFleetResponse.ProtoReflect.Descriptor instead.
func (*RemoveCarFromFleetResponse) Descriptor() ([]byte, []int) {
	return file_src_api_specification_api_specification_am_fleet_management_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveCarFromFleetResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *RemoveCarFromFleetResponse) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type ViewCarInformationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vin *Vin `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
}

func (x *ViewCarInformationRequest) Reset() {
	*x = ViewCarInformationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewCarInformationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewCarInformationRequest) ProtoMessage() {}

func (x *ViewCarInformationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewCarInformationRequest.ProtoReflect.Descriptor instead.
func (*ViewCarInformationRequest) Descriptor() ([]byte, []int) {
	return file_src_api_specification_api_specification_am_fleet_management_proto_rawDescGZIP(), []int{6}
}

func (x *ViewCarInformationRequest) GetVin() *Vin {
	if x != nil {
		return x.Vin
	}
	return nil
}

type ViewCarInformationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Car   *Car         `protobuf:"bytes,1,opt,name=car,proto3" json:"car,omitempty"`
	Error *ErrorDetail `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ViewCarInformationResponse) Reset() {
	*x = ViewCarInformationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewCarInformationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewCarInformationResponse) ProtoMessage() {}

func (x *ViewCarInformationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewCarInformationResponse.ProtoReflect.Descriptor instead.
func (*ViewCarInformationResponse) Descriptor() ([]byte, []int) {
	return file_src_api_specification_api_specification_am_fleet_management_proto_rawDescGZIP(), []int{7}
}

func (x *ViewCarInformationResponse) GetCar() *Car {
	if x != nil {
		return x.Car
	}
	return nil
}

func (x *ViewCarInformationResponse) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type Vin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vin string `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
}

func (x *Vin) Reset() {
	*x = Vin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vin) ProtoMessage() {}

func (x *Vin) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vin.ProtoReflect.Descriptor instead.
func (*Vin) Descriptor() ([]byte, []int) {
	return file_src_api_specification_api_specification_am_fleet_management_proto_rawDescGZIP(), []int{8}
}

func (x *Vin) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

type Car struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vin   *Vin   `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	Brand string `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	Model string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
}

func (x *Car) Reset() {
	*x = Car{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Car) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Car) ProtoMessage() {}

func (x *Car) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Car.ProtoReflect.Descriptor instead.
func (*Car) Descriptor() ([]byte, []int) {
	return file_src_api_specification_api_specification_am_fleet_management_proto_rawDescGZIP(), []int{9}
}

func (x *Car) GetVin() *Vin {
	if x != nil {
		return x.Vin
	}
	return nil
}

func (x *Car) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Car) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type Fleet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FleetId      string `protobuf:"bytes,1,opt,name=fleetId,proto3" json:"fleetId,omitempty"`
	Cars         []*Car `protobuf:"bytes,2,rep,name=cars,proto3" json:"cars,omitempty"`
	Location     string `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	FleetManager string `protobuf:"bytes,4,opt,name=fleetManager,proto3" json:"fleetManager,omitempty"`
}

func (x *Fleet) Reset() {
	*x = Fleet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fleet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fleet) ProtoMessage() {}

func (x *Fleet) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fleet.ProtoReflect.Descriptor instead.
func (*Fleet) Descriptor() ([]byte, []int) {
	return file_src_api_specification_api_specification_am_fleet_management_proto_rawDescGZIP(), []int{10}
}

func (x *Fleet) GetFleetId() string {
	if x != nil {
		return x.FleetId
	}
	return ""
}

func (x *Fleet) GetCars() []*Car {
	if x != nil {
		return x.Cars
	}
	return nil
}

func (x *Fleet) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Fleet) GetFleetManager() string {
	if x != nil {
		return x.FleetManager
	}
	return ""
}

type ErrorDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Details string `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_src_api_specification_api_specification_am_fleet_management_proto_rawDescGZIP(), []int{11}
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetail) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

var File_src_api_specification_api_specification_am_fleet_management_proto protoreflect.FileDescriptor

var file_src_api_specification_api_specification_am_fleet_management_proto_rawDesc = []byte{
	0x0a, 0x41, 0x73, 0x72, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x5f, 0x73, 0x70, 0x65, 0x63,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x6d, 0x5f, 0x66, 0x6c, 0x65,
	0x65, 0x74, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x22, 0x74, 0x0a, 0x14, 0x41, 0x64, 0x64, 0x43, 0x61, 0x72, 0x54, 0x6f,
	0x46, 0x6c, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x03,
	0x76, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x66, 0x6c, 0x65, 0x65,
	0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x56, 0x69, 0x6e, 0x52,
	0x03, 0x76, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x73, 0x0a, 0x15, 0x41, 0x64,
	0x64, 0x43, 0x61, 0x72, 0x54, 0x6f, 0x46, 0x6c, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x03, 0x63, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x52, 0x03, 0x63, 0x61, 0x72, 0x12, 0x32, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x66, 0x6c, 0x65,
	0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22,
	0x32, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x72, 0x73, 0x49, 0x6e, 0x46, 0x6c, 0x65,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x6c, 0x65,
	0x65, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x6c, 0x65, 0x65,
	0x74, 0x49, 0x64, 0x22, 0x77, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x72, 0x73, 0x49,
	0x6e, 0x46, 0x6c, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28,
	0x0a, 0x04, 0x63, 0x61, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x66,
	0x6c, 0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x43,
	0x61, 0x72, 0x52, 0x04, 0x63, 0x61, 0x72, 0x73, 0x12, 0x32, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x43, 0x0a, 0x19,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x61, 0x72, 0x46, 0x72, 0x6f, 0x6d, 0x46, 0x6c, 0x65,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x03, 0x76, 0x69, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x56, 0x69, 0x6e, 0x52, 0x03, 0x76, 0x69,
	0x6e, 0x22, 0x68, 0x0a, 0x1a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x61, 0x72, 0x46, 0x72,
	0x6f, 0x6d, 0x46, 0x6c, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x32, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x43, 0x0a, 0x19, 0x56,
	0x69, 0x65, 0x77, 0x43, 0x61, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x03, 0x76, 0x69, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x56, 0x69, 0x6e, 0x52, 0x03, 0x76, 0x69, 0x6e,
	0x22, 0x78, 0x0a, 0x1a, 0x56, 0x69, 0x65, 0x77, 0x43, 0x61, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26,
	0x0a, 0x03, 0x63, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x66, 0x6c,
	0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x61,
	0x72, 0x52, 0x03, 0x63, 0x61, 0x72, 0x12, 0x32, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x17, 0x0a, 0x03, 0x56, 0x69,
	0x6e, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x76, 0x69, 0x6e, 0x22, 0x59, 0x0a, 0x03, 0x43, 0x61, 0x72, 0x12, 0x26, 0x0a, 0x03, 0x76, 0x69,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x56, 0x69, 0x6e, 0x52, 0x03, 0x76,
	0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x8b,
	0x01, 0x0a, 0x05, 0x46, 0x6c, 0x65, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x6c, 0x65, 0x65,
	0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x6c, 0x65, 0x65, 0x74,
	0x49, 0x64, 0x12, 0x28, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x52, 0x04, 0x63, 0x61, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x66, 0x6c, 0x65, 0x65,
	0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x66, 0x6c, 0x65, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x22, 0x41, 0x0a, 0x0b,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x32,
	0xc9, 0x02, 0x0a, 0x0c, 0x46, 0x6c, 0x65, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x60, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x43, 0x61, 0x72, 0x54, 0x6f, 0x46, 0x6c, 0x65, 0x65,
	0x74, 0x12, 0x25, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x61, 0x72, 0x54, 0x6f, 0x46, 0x6c, 0x65, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x61,
	0x72, 0x54, 0x6f, 0x46, 0x6c, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x66, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x72, 0x73, 0x49, 0x6e,
	0x46, 0x6c, 0x65, 0x65, 0x74, 0x12, 0x27, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x72, 0x73,
	0x49, 0x6e, 0x46, 0x6c, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28,
	0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x72, 0x73, 0x49, 0x6e, 0x46, 0x6c, 0x65, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6f, 0x0a, 0x12, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x43, 0x61, 0x72, 0x46, 0x72, 0x6f, 0x6d, 0x46, 0x6c, 0x65, 0x65, 0x74,
	0x12, 0x2a, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x61, 0x72, 0x46, 0x72, 0x6f, 0x6d,
	0x46, 0x6c, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x66,
	0x6c, 0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x61, 0x72, 0x46, 0x72, 0x6f, 0x6d, 0x46, 0x6c, 0x65, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x7d, 0x0a, 0x0a, 0x43,
	0x61, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6f, 0x0a, 0x12, 0x56, 0x69, 0x65,
	0x77, 0x43, 0x61, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x2a, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x43, 0x61, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x66, 0x6c,
	0x65, 0x65, 0x74, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x56, 0x69,
	0x65, 0x77, 0x43, 0x61, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_api_specification_api_specification_am_fleet_management_proto_rawDescOnce sync.Once
	file_src_api_specification_api_specification_am_fleet_management_proto_rawDescData = file_src_api_specification_api_specification_am_fleet_management_proto_rawDesc
)

func file_src_api_specification_api_specification_am_fleet_management_proto_rawDescGZIP() []byte {
	file_src_api_specification_api_specification_am_fleet_management_proto_rawDescOnce.Do(func() {
		file_src_api_specification_api_specification_am_fleet_management_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_api_specification_api_specification_am_fleet_management_proto_rawDescData)
	})
	return file_src_api_specification_api_specification_am_fleet_management_proto_rawDescData
}

var file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_src_api_specification_api_specification_am_fleet_management_proto_goTypes = []interface{}{
	(*AddCarToFleetRequest)(nil),       // 0: fleetmanagement.AddCarToFleetRequest
	(*AddCarToFleetResponse)(nil),      // 1: fleetmanagement.AddCarToFleetResponse
	(*ListCarsInFleetRequest)(nil),     // 2: fleetmanagement.ListCarsInFleetRequest
	(*ListCarsInFleetResponse)(nil),    // 3: fleetmanagement.ListCarsInFleetResponse
	(*RemoveCarFromFleetRequest)(nil),  // 4: fleetmanagement.RemoveCarFromFleetRequest
	(*RemoveCarFromFleetResponse)(nil), // 5: fleetmanagement.RemoveCarFromFleetResponse
	(*ViewCarInformationRequest)(nil),  // 6: fleetmanagement.ViewCarInformationRequest
	(*ViewCarInformationResponse)(nil), // 7: fleetmanagement.ViewCarInformationResponse
	(*Vin)(nil),                        // 8: fleetmanagement.Vin
	(*Car)(nil),                        // 9: fleetmanagement.Car
	(*Fleet)(nil),                      // 10: fleetmanagement.Fleet
	(*ErrorDetail)(nil),                // 11: fleetmanagement.ErrorDetail
}
var file_src_api_specification_api_specification_am_fleet_management_proto_depIdxs = []int32{
	8,  // 0: fleetmanagement.AddCarToFleetRequest.vin:type_name -> fleetmanagement.Vin
	9,  // 1: fleetmanagement.AddCarToFleetResponse.car:type_name -> fleetmanagement.Car
	11, // 2: fleetmanagement.AddCarToFleetResponse.error:type_name -> fleetmanagement.ErrorDetail
	9,  // 3: fleetmanagement.ListCarsInFleetResponse.cars:type_name -> fleetmanagement.Car
	11, // 4: fleetmanagement.ListCarsInFleetResponse.error:type_name -> fleetmanagement.ErrorDetail
	8,  // 5: fleetmanagement.RemoveCarFromFleetRequest.vin:type_name -> fleetmanagement.Vin
	11, // 6: fleetmanagement.RemoveCarFromFleetResponse.error:type_name -> fleetmanagement.ErrorDetail
	8,  // 7: fleetmanagement.ViewCarInformationRequest.vin:type_name -> fleetmanagement.Vin
	9,  // 8: fleetmanagement.ViewCarInformationResponse.car:type_name -> fleetmanagement.Car
	11, // 9: fleetmanagement.ViewCarInformationResponse.error:type_name -> fleetmanagement.ErrorDetail
	8,  // 10: fleetmanagement.Car.vin:type_name -> fleetmanagement.Vin
	9,  // 11: fleetmanagement.Fleet.cars:type_name -> fleetmanagement.Car
	0,  // 12: fleetmanagement.FleetService.AddCarToFleet:input_type -> fleetmanagement.AddCarToFleetRequest
	2,  // 13: fleetmanagement.FleetService.ListCarsInFleet:input_type -> fleetmanagement.ListCarsInFleetRequest
	4,  // 14: fleetmanagement.FleetService.RemoveCarFromFleet:input_type -> fleetmanagement.RemoveCarFromFleetRequest
	6,  // 15: fleetmanagement.CarService.ViewCarInformation:input_type -> fleetmanagement.ViewCarInformationRequest
	1,  // 16: fleetmanagement.FleetService.AddCarToFleet:output_type -> fleetmanagement.AddCarToFleetResponse
	3,  // 17: fleetmanagement.FleetService.ListCarsInFleet:output_type -> fleetmanagement.ListCarsInFleetResponse
	5,  // 18: fleetmanagement.FleetService.RemoveCarFromFleet:output_type -> fleetmanagement.RemoveCarFromFleetResponse
	7,  // 19: fleetmanagement.CarService.ViewCarInformation:output_type -> fleetmanagement.ViewCarInformationResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_src_api_specification_api_specification_am_fleet_management_proto_init() }
func file_src_api_specification_api_specification_am_fleet_management_proto_init() {
	if File_src_api_specification_api_specification_am_fleet_management_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddCarToFleetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddCarToFleetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCarsInFleetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCarsInFleetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveCarFromFleetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveCarFromFleetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewCarInformationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewCarInformationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Car); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fleet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_api_specification_api_specification_am_fleet_management_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_src_api_specification_api_specification_am_fleet_management_proto_goTypes,
		DependencyIndexes: file_src_api_specification_api_specification_am_fleet_management_proto_depIdxs,
		MessageInfos:      file_src_api_specification_api_specification_am_fleet_management_proto_msgTypes,
	}.Build()
	File_src_api_specification_api_specification_am_fleet_management_proto = out.File
	file_src_api_specification_api_specification_am_fleet_management_proto_rawDesc = nil
	file_src_api_specification_api_specification_am_fleet_management_proto_goTypes = nil
	file_src_api_specification_api_specification_am_fleet_management_proto_depIdxs = nil
}
