//AM-RentalManagementV2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: api_specification_am_rental_management.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RentalsCollectionService_ListAvailableCars_FullMethodName   = "/rentalmanagement.RentalsCollectionService/ListAvailableCars"
	RentalsCollectionService_ListCarRentals_FullMethodName      = "/rentalmanagement.RentalsCollectionService/ListCarRentals"
	RentalsCollectionService_ListCustomerRentals_FullMethodName = "/rentalmanagement.RentalsCollectionService/ListCustomerRentals"
)

// RentalsCollectionServiceClient is the client API for RentalsCollectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RentalsCollectionServiceClient interface {
	ListAvailableCars(ctx context.Context, in *ListAvailableCarsRequest, opts ...grpc.CallOption) (*ListAvailableCarsResponse, error)
	ListCarRentals(ctx context.Context, in *ListCarRentalsRequest, opts ...grpc.CallOption) (*ListCarRentalsResponse, error)
	ListCustomerRentals(ctx context.Context, in *ListCustomerRentalsRequest, opts ...grpc.CallOption) (*ListCustomerRentalsResponse, error)
}

type rentalsCollectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRentalsCollectionServiceClient(cc grpc.ClientConnInterface) RentalsCollectionServiceClient {
	return &rentalsCollectionServiceClient{cc}
}

func (c *rentalsCollectionServiceClient) ListAvailableCars(ctx context.Context, in *ListAvailableCarsRequest, opts ...grpc.CallOption) (*ListAvailableCarsResponse, error) {
	out := new(ListAvailableCarsResponse)
	err := c.cc.Invoke(ctx, RentalsCollectionService_ListAvailableCars_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentalsCollectionServiceClient) ListCarRentals(ctx context.Context, in *ListCarRentalsRequest, opts ...grpc.CallOption) (*ListCarRentalsResponse, error) {
	out := new(ListCarRentalsResponse)
	err := c.cc.Invoke(ctx, RentalsCollectionService_ListCarRentals_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentalsCollectionServiceClient) ListCustomerRentals(ctx context.Context, in *ListCustomerRentalsRequest, opts ...grpc.CallOption) (*ListCustomerRentalsResponse, error) {
	out := new(ListCustomerRentalsResponse)
	err := c.cc.Invoke(ctx, RentalsCollectionService_ListCustomerRentals_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RentalsCollectionServiceServer is the server API for RentalsCollectionService service.
// All implementations must embed UnimplementedRentalsCollectionServiceServer
// for forward compatibility
type RentalsCollectionServiceServer interface {
	ListAvailableCars(context.Context, *ListAvailableCarsRequest) (*ListAvailableCarsResponse, error)
	ListCarRentals(context.Context, *ListCarRentalsRequest) (*ListCarRentalsResponse, error)
	ListCustomerRentals(context.Context, *ListCustomerRentalsRequest) (*ListCustomerRentalsResponse, error)
	mustEmbedUnimplementedRentalsCollectionServiceServer()
}

// UnimplementedRentalsCollectionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRentalsCollectionServiceServer struct {
}

func (UnimplementedRentalsCollectionServiceServer) ListAvailableCars(context.Context, *ListAvailableCarsRequest) (*ListAvailableCarsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAvailableCars not implemented")
}
func (UnimplementedRentalsCollectionServiceServer) ListCarRentals(context.Context, *ListCarRentalsRequest) (*ListCarRentalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCarRentals not implemented")
}
func (UnimplementedRentalsCollectionServiceServer) ListCustomerRentals(context.Context, *ListCustomerRentalsRequest) (*ListCustomerRentalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCustomerRentals not implemented")
}
func (UnimplementedRentalsCollectionServiceServer) mustEmbedUnimplementedRentalsCollectionServiceServer() {
}

// UnsafeRentalsCollectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RentalsCollectionServiceServer will
// result in compilation errors.
type UnsafeRentalsCollectionServiceServer interface {
	mustEmbedUnimplementedRentalsCollectionServiceServer()
}

func RegisterRentalsCollectionServiceServer(s grpc.ServiceRegistrar, srv RentalsCollectionServiceServer) {
	s.RegisterService(&RentalsCollectionService_ServiceDesc, srv)
}

func _RentalsCollectionService_ListAvailableCars_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAvailableCarsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentalsCollectionServiceServer).ListAvailableCars(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RentalsCollectionService_ListAvailableCars_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentalsCollectionServiceServer).ListAvailableCars(ctx, req.(*ListAvailableCarsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentalsCollectionService_ListCarRentals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCarRentalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentalsCollectionServiceServer).ListCarRentals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RentalsCollectionService_ListCarRentals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentalsCollectionServiceServer).ListCarRentals(ctx, req.(*ListCarRentalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentalsCollectionService_ListCustomerRentals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCustomerRentalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentalsCollectionServiceServer).ListCustomerRentals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RentalsCollectionService_ListCustomerRentals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentalsCollectionServiceServer).ListCustomerRentals(ctx, req.(*ListCustomerRentalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RentalsCollectionService_ServiceDesc is the grpc.ServiceDesc for RentalsCollectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RentalsCollectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rentalmanagement.RentalsCollectionService",
	HandlerType: (*RentalsCollectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAvailableCars",
			Handler:    _RentalsCollectionService_ListAvailableCars_Handler,
		},
		{
			MethodName: "ListCarRentals",
			Handler:    _RentalsCollectionService_ListCarRentals_Handler,
		},
		{
			MethodName: "ListCustomerRentals",
			Handler:    _RentalsCollectionService_ListCustomerRentals_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api_specification_am_rental_management.proto",
}

const (
	RentableCarsCollectionService_AddCarToRental_FullMethodName    = "/rentalmanagement.RentableCarsCollectionService/AddCarToRental"
	RentableCarsCollectionService_RemoveRentableCar_FullMethodName = "/rentalmanagement.RentableCarsCollectionService/RemoveRentableCar"
)

// RentableCarsCollectionServiceClient is the client API for RentableCarsCollectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RentableCarsCollectionServiceClient interface {
	AddCarToRental(ctx context.Context, in *AddCarToRentalRequest, opts ...grpc.CallOption) (*AddCarToRentalResponse, error)
	RemoveRentableCar(ctx context.Context, in *RemoveRentableCarRequest, opts ...grpc.CallOption) (*RemoveRentableCarResponse, error)
}

type rentableCarsCollectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRentableCarsCollectionServiceClient(cc grpc.ClientConnInterface) RentableCarsCollectionServiceClient {
	return &rentableCarsCollectionServiceClient{cc}
}

func (c *rentableCarsCollectionServiceClient) AddCarToRental(ctx context.Context, in *AddCarToRentalRequest, opts ...grpc.CallOption) (*AddCarToRentalResponse, error) {
	out := new(AddCarToRentalResponse)
	err := c.cc.Invoke(ctx, RentableCarsCollectionService_AddCarToRental_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rentableCarsCollectionServiceClient) RemoveRentableCar(ctx context.Context, in *RemoveRentableCarRequest, opts ...grpc.CallOption) (*RemoveRentableCarResponse, error) {
	out := new(RemoveRentableCarResponse)
	err := c.cc.Invoke(ctx, RentableCarsCollectionService_RemoveRentableCar_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RentableCarsCollectionServiceServer is the server API for RentableCarsCollectionService service.
// All implementations must embed UnimplementedRentableCarsCollectionServiceServer
// for forward compatibility
type RentableCarsCollectionServiceServer interface {
	AddCarToRental(context.Context, *AddCarToRentalRequest) (*AddCarToRentalResponse, error)
	RemoveRentableCar(context.Context, *RemoveRentableCarRequest) (*RemoveRentableCarResponse, error)
	mustEmbedUnimplementedRentableCarsCollectionServiceServer()
}

// UnimplementedRentableCarsCollectionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRentableCarsCollectionServiceServer struct {
}

func (UnimplementedRentableCarsCollectionServiceServer) AddCarToRental(context.Context, *AddCarToRentalRequest) (*AddCarToRentalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCarToRental not implemented")
}
func (UnimplementedRentableCarsCollectionServiceServer) RemoveRentableCar(context.Context, *RemoveRentableCarRequest) (*RemoveRentableCarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveRentableCar not implemented")
}
func (UnimplementedRentableCarsCollectionServiceServer) mustEmbedUnimplementedRentableCarsCollectionServiceServer() {
}

// UnsafeRentableCarsCollectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RentableCarsCollectionServiceServer will
// result in compilation errors.
type UnsafeRentableCarsCollectionServiceServer interface {
	mustEmbedUnimplementedRentableCarsCollectionServiceServer()
}

func RegisterRentableCarsCollectionServiceServer(s grpc.ServiceRegistrar, srv RentableCarsCollectionServiceServer) {
	s.RegisterService(&RentableCarsCollectionService_ServiceDesc, srv)
}

func _RentableCarsCollectionService_AddCarToRental_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCarToRentalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentableCarsCollectionServiceServer).AddCarToRental(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RentableCarsCollectionService_AddCarToRental_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentableCarsCollectionServiceServer).AddCarToRental(ctx, req.(*AddCarToRentalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RentableCarsCollectionService_RemoveRentableCar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRentableCarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RentableCarsCollectionServiceServer).RemoveRentableCar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RentableCarsCollectionService_RemoveRentableCar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RentableCarsCollectionServiceServer).RemoveRentableCar(ctx, req.(*RemoveRentableCarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RentableCarsCollectionService_ServiceDesc is the grpc.ServiceDesc for RentableCarsCollectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RentableCarsCollectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rentalmanagement.RentableCarsCollectionService",
	HandlerType: (*RentableCarsCollectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddCarToRental",
			Handler:    _RentableCarsCollectionService_AddCarToRental_Handler,
		},
		{
			MethodName: "RemoveRentableCar",
			Handler:    _RentableCarsCollectionService_RemoveRentableCar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api_specification_am_rental_management.proto",
}

const (
	CustomerService_RentCar_FullMethodName      = "/rentalmanagement.CustomerService/RentCar"
	CustomerService_CancelRental_FullMethodName = "/rentalmanagement.CustomerService/CancelRental"
)

// CustomerServiceClient is the client API for CustomerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CustomerServiceClient interface {
	RentCar(ctx context.Context, in *RentCarRequest, opts ...grpc.CallOption) (*RentCarResponse, error)
	CancelRental(ctx context.Context, in *CancelRentalRequest, opts ...grpc.CallOption) (*CancelRentalResponse, error)
}

type customerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomerServiceClient(cc grpc.ClientConnInterface) CustomerServiceClient {
	return &customerServiceClient{cc}
}

func (c *customerServiceClient) RentCar(ctx context.Context, in *RentCarRequest, opts ...grpc.CallOption) (*RentCarResponse, error) {
	out := new(RentCarResponse)
	err := c.cc.Invoke(ctx, CustomerService_RentCar_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) CancelRental(ctx context.Context, in *CancelRentalRequest, opts ...grpc.CallOption) (*CancelRentalResponse, error) {
	out := new(CancelRentalResponse)
	err := c.cc.Invoke(ctx, CustomerService_CancelRental_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerServiceServer is the server API for CustomerService service.
// All implementations must embed UnimplementedCustomerServiceServer
// for forward compatibility
type CustomerServiceServer interface {
	RentCar(context.Context, *RentCarRequest) (*RentCarResponse, error)
	CancelRental(context.Context, *CancelRentalRequest) (*CancelRentalResponse, error)
	mustEmbedUnimplementedCustomerServiceServer()
}

// UnimplementedCustomerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCustomerServiceServer struct {
}

func (UnimplementedCustomerServiceServer) RentCar(context.Context, *RentCarRequest) (*RentCarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RentCar not implemented")
}
func (UnimplementedCustomerServiceServer) CancelRental(context.Context, *CancelRentalRequest) (*CancelRentalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelRental not implemented")
}
func (UnimplementedCustomerServiceServer) mustEmbedUnimplementedCustomerServiceServer() {}

// UnsafeCustomerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomerServiceServer will
// result in compilation errors.
type UnsafeCustomerServiceServer interface {
	mustEmbedUnimplementedCustomerServiceServer()
}

func RegisterCustomerServiceServer(s grpc.ServiceRegistrar, srv CustomerServiceServer) {
	s.RegisterService(&CustomerService_ServiceDesc, srv)
}

func _CustomerService_RentCar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RentCarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).RentCar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerService_RentCar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).RentCar(ctx, req.(*RentCarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_CancelRental_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRentalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).CancelRental(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerService_CancelRental_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).CancelRental(ctx, req.(*CancelRentalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CustomerService_ServiceDesc is the grpc.ServiceDesc for CustomerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CustomerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rentalmanagement.CustomerService",
	HandlerType: (*CustomerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RentCar",
			Handler:    _CustomerService_RentCar_Handler,
		},
		{
			MethodName: "CancelRental",
			Handler:    _CustomerService_CancelRental_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api_specification_am_rental_management.proto",
}
