// Package controller provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package controller

// Car defines model for car.
type Car struct {
	// Brand Brand of a car
	Brand *string `json:"brand,omitempty"`

	// Model Model of a car
	Model *string `json:"model,omitempty"`

	// Vin Identifier of a car
	Vin *Vin `json:"vin,omitempty"`
}

// Vin Identifier of a car
type Vin = string
